name: SpendZero
options:
  bundleIdPrefix: com.clawdbonzo
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
  developmentLanguage: en
settings:
  base:
    SWIFT_EMIT_LOC_STRINGS: "YES"
    DEVELOPMENT_TEAM: "3N9RY9EG8V"
    MARKETING_VERSION: "1.1"
    CURRENT_PROJECT_VERSION: "6"
packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    from: 5.0.0
targets:
  SpendZero:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: SpendZero
        includes:
          - "**/*.swift"
      - path: SpendZero/Assets.xcassets
      - path: Resources
    info:
      path: SpendZero/Info.plist
      useBaseLocalizationAsSource: true
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "6"
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleLocalizations:
          - en
          - de
          - nl
          - pt-BR
          - fr-CA
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.clawdbonzo.SpendZero
      PRODUCT_NAME: SpendZero
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: "3N9RY9EG8V"
      CODE_SIGN_IDENTITY: "Apple Distribution"
      PROVISIONING_PROFILE_SPECIFIER: "SpendZero AppStore Manual"
      CURRENT_PROJECT_VERSION: "6"
      MARKETING_VERSION: "1.1"
      TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: RevenueCat
        product: RevenueCat
schemes:
  SpendZero:
    build:
      targets:
        SpendZero: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
